#!/bin/bash
# MAIN STATEMAPPER BASH SCRIPT

# nice levels for this script (the higher, the less priority)
IONICE=3
NICE=19

# STOP EDITING BELOW!




# find out what the Apache user is (to later execute PHP with it)
APACHE_USER=$(ps -ef | egrep '(httpd|apache2|apache)' 2> /dev/null | grep -v `whoami` 2> /dev/null | grep -v root 2> /dev/null | head -n1 | awk '{print $1}' 2> /dev/null)

CMD=$1
BASE_DIR=$(dirname "$0")

# change the nice levels at your convenency (using the smallest now)
BASE_CMD="ionice -c $IONICE nice -n $NICE php $BASE_DIR/../index.php"
PHP_CMD="$BASE_CMD $*"

function contains {
  local list="$1"
  local item="$2"
  if [[ $list =~ (^|[[:space:]])"$item"($|[[:space:]]) ]] ; then
    # yes, list include item
    result=0
  else
    result=1
  fi
  return $result
}

# grab Ctrl+C and interrupt the call beautifully
trap stop INT TSTP
stty -echo -icanon time 2 || exit $?

function stop {
	echo "User interruption, plan unexpected results!"
	exit 0
}

# git shortcuts
if [ "$CMD" = "push" ]
then
	cd "$BASE_DIR/.."
	sudo su - $APACHE_USER -s /bin/bash -c "$BASE_CMD compile" # compile manuals
	
	git add *
	if [ "$2" = "-m" ]
	then
		git commit -m "$3"
	else
		git commit
	fi
	git push
	exit
fi
if [ "$CMD" = "pull" ]
then
	cd "$BASE_DIR/.." && git pull
	exit
fi

# daemon
if [ "$CMD" = "daemon" ]
then
	# daemonizing
	DAEMON_CMD="$2"
	
	if [ -f "$BASE_DIR/.statemapper.lock" ]
	then
		PID=$(cat $BASE_DIR/.statemapper.lock)
		if [ "$PID" != "" ]
		then
			if ps -p "$PID" > /dev/null 2>&1
			then
				# print the daemon status
				if [ "$DAEMON_CMD" = "status" ]
				then
					echo "StateMapper daemon running with PID $PID"
					exit 0
				fi
				
				# kill the daemon
				if [ "$DAEMON_CMD" = "kill" ]
				then
					sudo kill -9 "$PID" 
					rm "$BASE_DIR/.statemapper.lock"
					echo "StateMapper daemon killed"
					exit 0
				fi
				
				# stop the daemon, waiting for workers
				if contains "stop restart" "$DAEMON_CMD"
				then
					sudo echo "Stopping the StateMapper daemon"
					sudo su - $APACHE_USER -s /bin/bash -c "$BASE_CMD daemon stop" 2> /dev/null
					if [ $? -eq 0 ]
					then
						rm "$BASE_DIR/.statemapper.lock"
						echo "StateMapper daemon stopped"
					else
						echo "Could not stop the StateMapper daemon"
					fi
					if [ "$DAEMON_CMD" = "stop" ]
					then
						exit 0
					else
						DAEMON_CMD="start"
					fi

				else
					echo "StateMapper daemon already running with PID $PID"
					exit 1
				fi
				
			fi
		fi
	fi

	# daemon is not running
	if contains "kill stop status" "$DAEMON_CMD"
	then
		echo "StateMapper daemon not running"
		exit 1
	fi
	
	if contains "-d -debug --d --debug" "$DAEMON_CMD"
	then
		# debug, not daemonized
		sudo echo "StateMapper daemon debugging.."
		PHP_CMD="$PHP_CMD "'echo "$!"'
		sudo su - $APACHE_USER -s /bin/bash -c "$PHP_CMD"
	else
	
		# daemonize and print PID into .lock file
		PHP_CMD="nohup $PHP_CMD >/dev/null 2>&1 &"'echo "$!"'
		sudo su - $APACHE_USER -s /bin/bash -c "$PHP_CMD" > $BASE_DIR/.statemapper.lock
		PID=$(cat $BASE_DIR/.statemapper.lock)
		echo "StateMapper daemon started with PID $PID"
	fi

else
	# not a daemon command, pass it to PHP
	sudo su - $APACHE_USER -s /bin/bash -c "$PHP_CMD"
fi

exit 0
